apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: {{ include "resource.name" . }}
  namespace: {{ include "resource.namespace" . }}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ include "resource.appName" . }}
        helm.sh/chart: {{ include "chart.chart" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}

    spec:
      containers:
      - name: {{ .Values.global.image.hummingbot.name }}
        image: {{ include "image.hummingbot.repository" . }}
        imagePullPolicy: {{ default "Always" .Values.global.image.hummingbot.imagepullPolicy }}
        args: [ "bash", "-c", "python3", "bin/hummingbot_quickstart.py" ]
        env: 
        - name: "CONFIG_PASSWORD"
          value: "Yoloswag420!"
        volumeMounts:
        - mountPath: /conf/conf_arb_39.yml
          name: config-vol
          subPath: conf_arb_39.yml
      imagePullSecrets:
      - name: {{ .Values.global.imagePullSecrets.default.name }}
      
      volumes:
      - name: config-vol
        configMap:
          name: {{ include "resource.name" . }}
          items:
          - key: conf_arb_39.yml
            path: conf_arb_39.yml 